# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-27 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0002_remove_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
